; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = rakwireless/boards

[env:rak4630]
platform = nordicnrf52
board = rak4630
framework = arduino
build_src_filter = ${env.build_src_filter}+<../rakwireless/variants/rak4630>
build_flags =
  -I rakwireless/variants/rak4630
  -DCODEC2_MODE_EN_DEFAULT=0
  -DCODEC2_MODE_2400_EN=1
  -D__EMBEDDED__
monitor_speed = 115200
